### ISSUE TITLE
Read counts in exp_matrix.txt but exp_matrix.rpkm.txt and exp_matrix.tpm.txt are empty

### ISSUE THREAD

**Issue by shkao** [sepro/LSTrAP#1]
Hi Sebastian,

What would be the possible reason that the read count matrix (exp_matrix.txt) is OK but exp_matrix.rpkm.txt and exp_matrix.tpm.txt are always empty?
Thanks in advance!

**Comment by sepro** [comment]
So TPM and RPKM normalize for read depth and the length of the transcripts. LSTrAP gets the length of the transcripts from the fasta file with coding sequences. 

I suspect this happens if there was no (valid) fasta file provided or the identifiers in the fasta file don't match the ones in the expression matrix.

**Comment by sepro** [comment]
Note that if this is the case the message "No sequence <gene_id>" should have been printed while running the pipeline.

Let me know if this solves your problem, so I can change that error to something more meaningful and close the issue.

**Comment by shkao** [comment]
Thank you, Sebastian.
>I suspect this happens if there was no (valid) fasta file provided or the identifiers in the fasta file don't match the ones in the expression matrix.

I followed this clue and deleted the description in my CDS fasta, for example: from `>Seq (2454) ;mRNA; r:60989-64666` to `>Seq`, and now it works. Perhaps make a built-in functionality in `pipeline/transcriptome.py` to sanitise the fasta?
